
# https://platform.openai.com/docs/pricing

gpt-4o: 
    input: 2.5 # 2.5 dollar per 1M tokens
    output: 10

gpt-4o-mini:
    input: 0.15
    output: 0.6

default:
    input: 0.15
    output: 0.6

gemini-2.5-pro:
    input: 1.25
    output: 10

gemini-2.5-flash:
    input: 0.3
    output: 2.5